//===========================================================================
//
// Name:			Xaero_c.c
// Function:		Xaero, rank 2
// Programmer:		MrElusive (MrElusive@idsoftware.com)
// version:			1
// Tab Size:		4 (real tabs)
//===========================================================================

#include "chars.h"

skill 1
{
	CHARACTERISTIC_NAME							"Xaero"
	CHARACTERISTIC_GENDER						"male"
	CHARACTERISTIC_ATTACK_SKILL					0.45
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/xaero_w.c"
	CHARACTERISTIC_AIM_SKILL					0.45
	CHARACTERISTIC_AIM_ACCURACY					0.75
	CHARACTERISTIC_VIEW_FACTOR					0.95
	CHARACTERISTIC_VIEW_MAXCHANGE				360
	CHARACTERISTIC_REACTIONTIME					0.5

	CHARACTERISTIC_CHAT_FILE					"bots/xaero_t.c"
	CHARACTERISTIC_CHAT_NAME					"xaero"
	CHARACTERISTIC_CHAT_CPM						400
	CHARACTERISTIC_CHAT_INSULT					0.4
	CHARACTERISTIC_CHAT_MISC					0.5
	CHARACTERISTIC_CHAT_STARTENDLEVEL			0.5
	CHARACTERISTIC_CHAT_ENTEREXITGAME			0.5
	CHARACTERISTIC_CHAT_KILL					0.5
	CHARACTERISTIC_CHAT_DEATH					0.5
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			0.5
	CHARACTERISTIC_CHAT_HITTALKING				0.15
	CHARACTERISTIC_CHAT_HITNODEATH				0.5
	CHARACTERISTIC_CHAT_HITNOKILL				0.5
	CHARACTERISTIC_CHAT_RANDOM					0.5
	CHARACTERISTIC_CHAT_REPLY					0.25

	CHARACTERISTIC_CROUCHER						0.05
	CHARACTERISTIC_JUMPER						0.95
	CHARACTERISTIC_WALKER						0.0
	CHARACTERISTIC_WEAPONJUMPING				0.05

	CHARACTERISTIC_ITEMWEIGHTS					"bots/xaero_i.c"
	CHARACTERISTIC_AGGRESSION					0.75
	CHARACTERISTIC_SELFPRESERVATION				0.95
	CHARACTERISTIC_VENGEFULNESS					0.95
	CHARACTERISTIC_CAMPER						0.25

	CHARACTERISTIC_EASY_FRAGGER					0.05
	CHARACTERISTIC_ALERTNESS					0.95

	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN		0.5
	CHARACTERISTIC_AIM_ACCURACY_PAIN_SAW		0.5
	CHARACTERISTIC_AIM_ACCURACY_SHOTGUN			0.5
	CHARACTERISTIC_AIM_ACCURACY_LAS_GUN			0.5
	CHARACTERISTIC_AIM_ACCURACY_MASS_DRIVER		0.7
	CHARACTERISTIC_AIM_ACCURACY_CHAINGUN		0.5
	CHARACTERISTIC_AIM_ACCURACY_PULSE_RIFLE		0.5
	CHARACTERISTIC_AIM_ACCURACY_FLAMER			0.5
	CHARACTERISTIC_AIM_ACCURACY_LUCIFERCANNON	0.5

	CHARACTERISTIC_FIRETHROTTLE					0.4
}

skill 4
{
	CHARACTERISTIC_NAME							"Xaero"
	CHARACTERISTIC_GENDER						"male"
	CHARACTERISTIC_ATTACK_SKILL					0.95
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/xaero_w.c"
	CHARACTERISTIC_AIM_SKILL					0.95
	CHARACTERISTIC_AIM_ACCURACY					0.95
	CHARACTERISTIC_VIEW_FACTOR					0.95
	CHARACTERISTIC_VIEW_MAXCHANGE				360
	CHARACTERISTIC_REACTIONTIME					0.5

	CHARACTERISTIC_CHAT_FILE					"bots/xaero_t.c"
	CHARACTERISTIC_CHAT_NAME					"xaero"
	CHARACTERISTIC_CHAT_CPM						400
	CHARACTERISTIC_CHAT_INSULT					0.4
	CHARACTERISTIC_CHAT_MISC					0.5
	CHARACTERISTIC_CHAT_STARTENDLEVEL			0.5
	CHARACTERISTIC_CHAT_ENTEREXITGAME			0.5
	CHARACTERISTIC_CHAT_KILL					0.5
	CHARACTERISTIC_CHAT_DEATH					0.5
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			0.5
	CHARACTERISTIC_CHAT_HITTALKING				0.15
	CHARACTERISTIC_CHAT_HITNODEATH				0.5
	CHARACTERISTIC_CHAT_HITNOKILL				0.5
	CHARACTERISTIC_CHAT_RANDOM					0.5
	CHARACTERISTIC_CHAT_REPLY					0.25

	CHARACTERISTIC_CROUCHER						0.05
	CHARACTERISTIC_JUMPER						0.95
	CHARACTERISTIC_WALKER						0.0
	CHARACTERISTIC_WEAPONJUMPING				0.05

	CHARACTERISTIC_ITEMWEIGHTS					"bots/xaero_i.c"
	CHARACTERISTIC_AGGRESSION					0.75
	CHARACTERISTIC_SELFPRESERVATION				0.95
	CHARACTERISTIC_VENGEFULNESS					0.95
	CHARACTERISTIC_CAMPER						0.25

	CHARACTERISTIC_EASY_FRAGGER					0.05
	CHARACTERISTIC_ALERTNESS					0.95

	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN		0.6
	CHARACTERISTIC_AIM_ACCURACY_PAIN_SAW		0.6
	CHARACTERISTIC_AIM_ACCURACY_SHOTGUN			0.6
	CHARACTERISTIC_AIM_ACCURACY_LAS_GUN			0.6
	CHARACTERISTIC_AIM_ACCURACY_MASS_DRIVER		0.8
	CHARACTERISTIC_AIM_ACCURACY_CHAINGUN		0.6
	CHARACTERISTIC_AIM_ACCURACY_PULSE_RIFLE		0.6
	CHARACTERISTIC_AIM_ACCURACY_FLAMER			0.6
	CHARACTERISTIC_AIM_ACCURACY_LUCIFERCANNON	0.6

	CHARACTERISTIC_FIRETHROTTLE					0.8
}

skill 5
{
	CHARACTERISTIC_NAME							"Xaero"
	CHARACTERISTIC_GENDER						"male"
	CHARACTERISTIC_ATTACK_SKILL					0.95
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/xaero_w.c"
	CHARACTERISTIC_AIM_SKILL					0.95
	CHARACTERISTIC_AIM_ACCURACY					0.95
	CHARACTERISTIC_VIEW_FACTOR					0.95
	CHARACTERISTIC_VIEW_MAXCHANGE				360
	CHARACTERISTIC_REACTIONTIME					0.5

	CHARACTERISTIC_CHAT_FILE					"bots/xaero_t.c"
	CHARACTERISTIC_CHAT_NAME					"xaero"
	CHARACTERISTIC_CHAT_CPM						400
	CHARACTERISTIC_CHAT_INSULT					0.4
	CHARACTERISTIC_CHAT_MISC					0.5
	CHARACTERISTIC_CHAT_STARTENDLEVEL			0.5
	CHARACTERISTIC_CHAT_ENTEREXITGAME			0.5
	CHARACTERISTIC_CHAT_KILL					0.5
	CHARACTERISTIC_CHAT_DEATH					0.5
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			0.5
	CHARACTERISTIC_CHAT_HITTALKING				0.1
	CHARACTERISTIC_CHAT_HITNODEATH				0.5
	CHARACTERISTIC_CHAT_HITNOKILL				0.5
	CHARACTERISTIC_CHAT_RANDOM					0.5
	CHARACTERISTIC_CHAT_REPLY					0.1

	CHARACTERISTIC_CROUCHER						0.05
	CHARACTERISTIC_JUMPER						0.95
	CHARACTERISTIC_WALKER						0.0
	CHARACTERISTIC_WEAPONJUMPING				0.05

	CHARACTERISTIC_ITEMWEIGHTS					"bots/xaero_i.c"
	CHARACTERISTIC_AGGRESSION					0.75
	CHARACTERISTIC_SELFPRESERVATION				0.95
	CHARACTERISTIC_VENGEFULNESS					0.95
	CHARACTERISTIC_CAMPER						0.25

	CHARACTERISTIC_EASY_FRAGGER					0.05
	CHARACTERISTIC_ALERTNESS					0.95

	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN		1.0
	CHARACTERISTIC_AIM_ACCURACY_PAIN_SAW		1.0
	CHARACTERISTIC_AIM_ACCURACY_SHOTGUN			1.0
	CHARACTERISTIC_AIM_ACCURACY_LAS_GUN			1.0
	CHARACTERISTIC_AIM_ACCURACY_MASS_DRIVER		1.0
	CHARACTERISTIC_AIM_ACCURACY_CHAINGUN		1.0
	CHARACTERISTIC_AIM_ACCURACY_PULSE_RIFLE		1.0
	CHARACTERISTIC_AIM_ACCURACY_FLAMER			1.0
	CHARACTERISTIC_AIM_ACCURACY_LUCIFERCANNON	1.0

	CHARACTERISTIC_FIRETHROTTLE					1.0
}